'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from 'lucide-react'

const steps = ['Basics', 'Skills', 'Experience', 'Service area', 'Languages', 'Certifications', 'Cooperative', 'Availability', 'Submit']

export default function WorkerJoinPage() {
  const [step, setStep] = useState(0)
  const [submitted, setSubmitted] = useState(false)
  if (submitted) return <main className="grid min-h-screen place-items-center bg-background px-5 text-center"><div className="max-w-md"><span className="mx-auto grid size-16 place-items-center rounded-3xl bg-primary text-primary-foreground"><Check className="size-8" /></span><h1 className="mt-6 font-serif text-4xl font-bold">Your profile is ready for review.</h1><p className="mt-4 leading-7 text-muted-foreground">SAHAYAK will verify your details before you receive requests. This protects you and the households you serve.</p><Link href="/" className="mt-8 inline-flex rounded-full bg-primary px-5 py-3 font-semibold text-primary-foreground">Back to SAHAYAK</Link></div></main>
  return <main className="min-h-screen bg-background px-5 py-8 text-foreground"><div className="mx-auto max-w-3xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" /> Back to SAHAYAK</Link><div className="mt-12"><p className="eyebrow">Worker onboarding</p><h1 className="mt-3 font-serif text-5xl font-bold tracking-tight">Turn your skill into a stronger livelihood.</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Complete your profile in a few steps. You remain pending verification until a cooperative or SAHAYAK reviewer approves your details.</p></div><div className="mt-10 overflow-x-auto"><div className="flex min-w-max gap-2">{steps.map((name, index) => <button key={name} onClick={() => setStep(index)} className={`rounded-full px-3 py-2 text-xs font-semibold ${index === step ? 'bg-primary text-primary-foreground' : index < step ? 'bg-secondary text-secondary-foreground' : 'bg-muted text-muted-foreground'}`}>{index + 1}. {name}</button>)}</div></div><section className="mt-8 rounded-[1.5rem] border border-border bg-card p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-secondary text-primary"><ShieldCheck className="size-5" /></span><div><p className="eyebrow">Step {step + 1} of {steps.length}</p><h2 className="mt-2 font-serif text-3xl font-bold">{steps[step]}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Add the information cooperatives use to match you with safe, suitable work.</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><Field label={step === 0 ? 'Full name' : step === 1 ? 'Primary skill' : step === 3 ? 'Service area' : step === 4 ? 'Languages spoken' : step === 7 ? 'Working hours' : 'Details'} placeholder={step === 0 ? 'Your full name' : 'Type your answer'} /><Field label="Notes (optional)" placeholder="Tell us anything useful" /></div><div className="mt-8 flex justify-between gap-3"><button disabled={step === 0} onClick={() => setStep((value) => value - 1)} className="rounded-full border border-border px-5 py-3 text-sm font-semibold disabled:opacity-40">Back</button>{step === steps.length - 1 ? <button onClick={() => setSubmitted(true)} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Submit for verification <Check className="size-4" /></button> : <button onClick={() => setStep((value) => value + 1)} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Continue <ArrowRight className="size-4" /></button>}</div></section></div></main>
}

function Field({ label, placeholder }: { label: string; placeholder: string }) { return <label className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{label}<input required={label === 'Full name'} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3 text-sm font-normal normal-case tracking-normal outline-none ring-primary focus:ring-2" /></label> }
