'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, Languages, MapPin, Star, Zap } from 'lucide-react'

const workers = [
  { name: 'Ravi Kumar', role: 'Home care specialist', rating: 4.9, distance: 2.4, languages: ['English', 'हिन्दी'], availability: 'Morning', service: 'Elder care' },
  { name: 'Meena Sharma', role: 'Cook & elder companion', rating: 5, distance: 4.7, languages: ['বাংলা', 'English'], availability: 'Flexible', service: 'Cooking help' },
  { name: 'Arjun Das', role: 'Repairs & maintenance', rating: 4.8, distance: 3.1, languages: ['English', 'বাংলা'], availability: 'Afternoon', service: 'Repairs & more' },
]
export default function MatchPage() {
  const [service, setService] = useState('Elder care')
  const [language, setLanguage] = useState('English')
  const [selected, setSelected] = useState('')
  const ranked = useMemo(() => [...workers].sort((a, b) => (Number(b.service === service) - Number(a.service === service)) * 10 + (Number(b.languages.includes(language)) - Number(a.languages.includes(language))) * 5 + b.rating - a.rating - (b.distance - a.distance) * 0.1), [service, language])
  return <main className="min-h-screen bg-background px-5 py-12"><div className="mx-auto max-w-5xl"><p className="eyebrow">Smart matching</p><h1 className="mt-2 max-w-2xl font-serif text-5xl font-bold">The right person for your everyday.</h1><p className="mt-4 max-w-xl text-muted-foreground">We rank trusted workers by service fit, language, distance, availability, and reviews.</p><div className="mt-8 grid gap-3 rounded-[2rem] border border-border bg-card p-5 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-semibold">Service<select value={service} onChange={(e) => setService(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal"><option>Elder care</option><option>Home cleaning</option><option>Cooking help</option><option>Repairs & more</option></select></label><label className="flex flex-col gap-2 text-sm font-semibold">Preferred language<select value={language} onChange={(e) => setLanguage(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3 font-normal"><option>English</option><option>हिन्दी</option><option>বাংলা</option></select></label></div><div className="mt-8 grid gap-4 md:grid-cols-3">{ranked.map((worker, index) => <article key={worker.name} className={`rounded-[1.75rem] border bg-card p-5 ${index === 0 ? 'border-primary shadow-lg shadow-primary/10' : 'border-border'}`}><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-primary text-lg font-bold text-primary-foreground">{worker.name.split(' ').map((part) => part[0]).join('')}</span>{index === 0 && <span className="rounded-full bg-accent px-3 py-1 text-xs font-bold text-accent-foreground">Best match</span>}</div><h2 className="mt-5 font-serif text-2xl font-bold">{worker.name}</h2><p className="text-sm text-muted-foreground">{worker.role}</p><div className="mt-5 grid gap-2 text-sm"><span className="flex items-center gap-2"><Star className="size-4 fill-accent text-accent" /> {worker.rating} rating</span><span className="flex items-center gap-2"><MapPin className="size-4 text-primary" /> {worker.distance} km away</span><span className="flex items-center gap-2"><Languages className="size-4 text-primary" /> {worker.languages.join(' · ')}</span><span className="flex items-center gap-2"><Zap className="size-4 text-primary" /> {worker.availability}</span></div><button onClick={() => setSelected(worker.name)} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary px-4 py-3 font-semibold text-primary-foreground">Choose {worker.name.split(' ')[0]} <ArrowRight className="size-4" /></button></article>)}</div>{selected && <div className="mt-6 flex items-center gap-3 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm font-semibold"><Check className="size-5 text-primary" /> {selected} selected. Start a booking to open a private chat.</div>}</div></main>
}
