import Link from 'next/link'
import { CalendarDays, ChevronRight, CircleHelp, CreditCard, Heart, MapPin, ShieldCheck } from 'lucide-react'
import { auth } from '@/lib/auth'
import { getMyBookings } from '@/app/actions/bookings'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'

export default async function DashboardPage() {
  const session = await auth.api.getSession({ headers: await headers() })
  if (!session?.user) redirect('/sign-in')
  const bookings = await getMyBookings()
  return <main className="min-h-screen bg-background px-5 py-8 text-foreground"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Customer dashboard</p><h1 className="mt-2 font-serif text-4xl font-bold">Good to see you, {session.user.name.split(' ')[0]}.</h1><p className="mt-2 text-muted-foreground">Keep track of help, payments, and your trusted circle.</p></div><Link href="/services" className="rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Book a service</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><DashboardLink href="#bookings" icon={CalendarDays} title="Bookings" detail={`${bookings.length} requests`} /><DashboardLink href="#saved" icon={Heart} title="Saved workers" detail="Build your circle" /><DashboardLink href="#payments" icon={CreditCard} title="Payments" detail="View invoices" /><DashboardLink href="#support" icon={CircleHelp} title="Support" detail="We have your back" /></div><section id="bookings" className="mt-10 rounded-[1.5rem] border border-border bg-card p-6"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Live booking lifecycle</p><h2 className="mt-2 font-serif text-3xl font-bold">Your requests</h2></div><MapPin className="size-6 text-primary" /></div>{bookings.length ? <div className="mt-6 flex flex-col gap-3">{bookings.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-border bg-background p-4"><div><p className="font-semibold">{item.service}</p><p className="mt-1 text-sm text-muted-foreground">{item.location} · {item.createdAt.toLocaleDateString()}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground">{item.status}</span></div>)}</div> : <div className="mt-6 rounded-2xl bg-secondary/50 p-6"><p className="font-semibold">No bookings yet</p><p className="mt-1 text-sm text-muted-foreground">Choose a service and your first request will appear here.</p><Link href="/services" className="mt-4 inline-flex rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Browse services</Link></div>}</section><section className="mt-6 grid gap-4 md:grid-cols-3"><InfoCard icon={ShieldCheck} title="Safety centre" text="Emergency support, worker verification, and clear help when you need it." /><InfoCard icon={MapPin} title="Saved addresses" text="Add home, work, or family locations for faster booking." /><InfoCard icon={CreditCard} title="Transparent payments" text="Review estimates, invoices, and worker earnings clearly." /></section></div></main>
}

function DashboardLink({ href, icon: Icon, title, detail }: { href: string; icon: typeof CalendarDays; title: string; detail: string }) { return <Link href={href} className="rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-0.5 hover:border-primary/40"><Icon className="size-5 text-primary" /><p className="mt-5 font-semibold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{detail}</p></Link> }
function InfoCard({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="rounded-2xl border border-border bg-card p-5"><Icon className="size-5 text-primary" /><p className="mt-5 font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div> }
